version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/plugins:/fluentd/plugins
      - ./fluentd/work:/fluentd/work
    links:
      - "elasticsearch"
    ports:
      - "24225:24225"
      - "24225:24225/udp"
    networks:
      yamada_net:
        ipv4_address: 182.18.1.11

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      yamada_net:
        ipv4_address: 182.18.1.12

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      yamada_net:
        ipv4_address: 182.18.1.13

networks:
  yamada_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 182.18.1.0/24